name: ahmed10
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  sqflite: ^2.0.0+4
  path: ^1.8.0
  firebase_core: ^2.26.0
  firebase_database: ^10.5.5
  connectivity_plus: ^4.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/mo.jpg"
