// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLjS3ajSUokFqvEuFmUD8s--BxMgYJmI',
    appId: '1:164643592222:android:f79b872d2597033f04b60f',
    messagingSenderId: '164643592222',
    projectId: 'ahmed10-9bc27',
    databaseURL: 'https://ahmed10-9bc27-default-rtdb.firebaseio.com',
    storageBucket: 'ahmed10-9bc27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDXUWuZwAvvgT8544fLyMO3qYkZpTVMhk',
    appId: '1:164643592222:ios:d13b027a0419543404b60f',
    messagingSenderId: '164643592222',
    projectId: 'ahmed10-9bc27',
    databaseURL: 'https://ahmed10-9bc27-default-rtdb.firebaseio.com',
    storageBucket: 'ahmed10-9bc27.firebasestorage.app',
    iosBundleId: 'com.example.ahmed10',
  );
}
